In [1]:
from numpy import genfromtxt

my_data = genfromtxt('export_utm.csv', delimiter=',')

In [2]:
my_data

array([[           nan,            nan,            nan,            nan],
       [7.60369837e+05, 1.43393579e+06, 7.74000000e+01, 1.29600000e+01],
       [7.73526254e+05, 1.42077941e+06, 7.75200000e+01, 1.28400000e+01],
       [7.73395753e+05, 1.43406130e+06, 7.75200000e+01, 1.29600000e+01],
       [7.73264058e+05, 1.44734329e+06, 7.75200000e+01, 1.30800000e+01],
       [7.73131169e+05, 1.46062537e+06, 7.75200000e+01, 1.32000000e+01],
       [7.86694976e+05, 1.40762699e+06, 7.76400000e+01, 1.27200000e+01],
       [7.86559492e+05, 1.42090992e+06, 7.76400000e+01, 1.28400000e+01],
       [7.86422756e+05, 1.43419295e+06, 7.76400000e+01, 1.29600000e+01],
       [7.86284769e+05, 1.44747607e+06, 7.76400000e+01, 1.30800000e+01],
       [7.86145531e+05, 1.46075928e+06, 7.76400000e+01, 1.32000000e+01],
       [7.99735536e+05, 1.40776241e+06, 7.77600000e+01, 1.27200000e+01],
       [7.99593871e+05, 1.42104653e+06, 7.77600000e+01, 1.28400000e+01],
       [7.99450897e+05, 1.43433074e+06, 7.77600000e+01, 1.29600000e+01],
       [7.99306615e+05, 1.44761505e+06, 7.77600000e+01, 1.30800000e+01]])

In [7]:
import pandas as pd
df = pd.read_excel('recess_coeff.xls.xlsx',header = None)
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,7.603698e+05,7.735263e+05,7.733958e+05,7.732641e+05,7.731312e+05,7.866950e+05,7.865595e+05,7.864228e+05,7.862848e+05,7.861455e+05,7.997355e+05,7.995939e+05,7.994509e+05,7.993066e+05
1,1.433936e+06,1.420779e+06,1.434061e+06,1.447343e+06,1.460625e+06,1.407627e+06,1.420910e+06,1.434193e+06,1.447476e+06,1.460759e+06,1.407762e+06,1.421047e+06,1.434331e+06,1.447615e+06
2,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
3,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
4,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
733,4.984375e+00,5.828125e+00,5.031250e+00,3.546875e+00,3.921875e+00,2.421875e+00,3.109375e+00,4.234375e+00,5.640625e+00,4.265625e+00,2.906250e+00,2.859375e+00,2.765625e+00,2.625000e+00
734,7.843750e+00,8.859375e+00,7.859375e+00,6.406250e+00,6.234375e+00,8.984375e+00,8.937500e+00,8.281250e+00,8.000000e+00,5.796875e+00,1.107812e+01,1.051562e+01,8.640625e+00,8.125000e+00
735,3.906250e-01,0.000000e+00,1.718750e-01,4.531250e-01,1.250000e-01,0.000000e+00,0.000000e+00,1.562500e-02,6.875000e-01,2.187500e-01,0.000000e+00,0.000000e+00,0.000000e+00,1.093750e-01
736,4.328125e+00,1.062500e+00,3.687500e+00,3.343750e+00,4.437500e+00,7.031250e-01,8.281250e-01,1.687500e+00,1.562500e+00,1.515625e+00,9.218750e-01,1.046875e+00,9.687500e-01,1.187500e+00
737,8.125000e-01,8.593750e-01,9.062500e-01,1.531250e+00,1.812500e+00,8.281250e-01,1.234375e+00,1.421875e+00,1.984375e+00,2.140625e+00,7.187500e-01,1.140625e+00,1.671875e+00,2.125000e+00

In [8]:
data = df.to_numpy()

In [9]:
data[1,1]

1420779.41149937

In [6]:
import math
beta = []
for i in range(2,738):
    max_value = np.max(data[i,:])
    if max_value > 0:
        max_index  = np.argmax(data[i,:])
        dist = np.zeros
        betaj = 0
        k  =0 
        if max_index >= 5:
            for j in range(max_index):
                x1 = data[0,max_index]
                y1 = data[1,max_index]
                x2 = data[0,j]
                y2 = data[1,j]
                dist = ((x2-x1)**2 + (y2-y1)**2)**(1/2)
                Px = data[i,j]; Po = max_value
                if Px != 0:
                    betaj += ((1/dist)*math.sqrt((-1/2) * math.log(Px/Po)))
                    k +=1
                    
            if k != 0:
                beta_avg = betaj/k
            else :
                for j in range(max_index+1,data.shape[1]):

                    x1 = data[0,max_index]
                    y1 = data[1,max_index]
                    x2 = data[0,j]
                    y2 = data[1,j]
                    dist = ((x2-x1)**2 + (y2-y1)**2)**(1/2)
                    Px = data[i,j]; Po = max_value
                    if Px != 0:
                        betaj += ((1/dist)*math.sqrt((-1/2) * math.log(Px/Po)))
                        k +=1
                
            

        else:
            for j in range(max_index+1,data.shape[1]):

                x1 = data[0,max_index]
                y1 = data[1,max_index]
                x2 = data[0,j]
                y2 = data[1,j]
                dist = ((x2-x1)**2 + (y2-y1)**2)**(1/2)
                Px = data[i,j]; Po = max_value
                if Px != 0:
                    betaj += ((1/dist)*math.sqrt((-1/2) * math.log(Px/Po)))
                    k +=1
            if k != 0:
                beta_avg = betaj/k
            else :
                for j in range(max_index):

                    x1 = data[0,max_index]
                    y1 = data[1,max_index]
                    x2 = data[0,j]
                    y2 = data[1,j]
                    dist = ((x2-x1)**2 + (y2-y1)**2)**(1/2)
                    Px = data[i,j]; Po = max_value
                    if Px != 0:
                        betaj += ((1/dist)*math.sqrt((-1/2) * math.log(Px/Po)))
                        k +=1

                beta_avg = betaj / k
        beta.append(beta_avg)
beta

NameError: name 'np' is not defined

In [ ]:
import math
import numpy as np
beta = []
for i in range(2,738):
    max_value = np.max(data[i,:])
    if max_value > 0:
        max_index  = np.argmax(data[i,:])
        
        betaj = 0
        k  =0 
        for j in range(max_index):
            x1 = data[0,max_index]
            y1 = data[1,max_index]
            x2 = data[0,j]
            y2 = data[1,j]
            dist = (((x2-x1)**2 + (y2-y1)**2)**(1/2))/1000
            Px = data[i,j]; Po = max_value
            if Px != 0:
                betaj += ((1/dist)*math.sqrt((-1/2) * math.log(Px/Po)))
                k = k+1
                beta_avg = betaj/k
        beta.append(beta_avg)
        
        if k == 0:
            for j in range(max_index+1,data.shape[1]):
                x1 = data[0,max_index]
                y1 = data[1,max_index]
                x2 = data[0,j]
                y2 = data[1,j]
                dist = (((x2-x1)**2 + (y2-y1)**2)**(1/2))/1000
                Px = data[i,j]; Po = max_value
                if Px != 0:
                    betaj += ((1/dist)*math.sqrt((-1/2) * math.log(Px/Po)))
                    k = k+1
                    beta_avg = betaj/k
            beta.append(beta_avg)
            
np.savetxt('beta.txt',beta)

In [ ]:
import numpy as np

max_value = np.max(data[1,:])
max_index  = np.argmax(data[1,:])
print(max_value)
max_index

In [ ]:
x = data.shape[0]
y = data.shape[1]
print(x, y )

In [13]:
df1 = pd.read_excel('recess_coeff.xls.xlsx',sheet_name = 1)
df1['Recess']
df1

       Recess  Unnamed: 1
0    0.063840           0
1    0.020382           0
2    0.022171           0
3    0.025569           0
4    0.025569           0
..        ...         ...
709  0.015029           0
710  0.012672           0
711  0.050237           0
712  0.016191           0
713  0.017662           0

[714 rows x 2 columns]

In [15]:
df1 = df1[df1.Recess != 0 ]
data1 = df1.to_numpy()
data1

array([[0.06384003, 0.        ],
       [0.02038221, 0.        ],
       [0.02217075, 0.        ],
       ...,
       [0.05023745, 0.        ],
       [0.01619122, 0.        ],
       [0.01766207, 0.        ]])

In [17]:
import numpy as np
np.savetxt('df1.txt',data1)

In [18]:
df = pd.read_csv (r'D:\IISc\Project\Stormbang\XxinYyin.csv')

In [19]:
df

,id,left,top,right,bottom,X,Y
0,60,744283.1126,1440478.389,746283.1126,1442478.389,745283.1126,1441478.389
1,61,744283.1126,1438478.389,746283.1126,1440478.389,745283.1126,1439478.389
2,62,744283.1126,1436478.389,746283.1126,1438478.389,745283.1126,1437478.389
3,63,744283.1126,1434478.389,746283.1126,1436478.389,745283.1126,1435478.389
4,64,744283.1126,1432478.389,746283.1126,1434478.389,745283.1126,1433478.389
...,...,...,...,...,...,...,...
1149,1578,816283.1126,1428478.389,818283.1126,1430478.389,817283.1126,1429478.389
1150,1579,816283.1126,1426478.389,818283.1126,1428478.389,817283.1126,1427478.389
1151,1580,816283.1126,1424478.389,818283.1126,1426478.389,817283.1126,1425478.389
1152,1581,816283.1126,1422478.389,818283.1126,1424478.389,817283.1126,1423478.389
1153,1582,816283.1126,1420478.389,818283.1126,1422478.389,817283.1126,1421478.389

In [20]:
Xin = df[['X']]

In [22]:
Xin.head()

             X
0  745283.1126
1  745283.1126
2  745283.1126
3  745283.1126
4  745283.1126

In [23]:
center_val_X = np.random.choice(Xin[0])

KeyError: 0